Repository stolostron/application-ui, pull requests merged in 2021-04, with the labels that each got.

#1061 ArgoCD setup for e2e tests
  tests/cypress/scripts/argocd-integration.sh
  tests/cypress/support/argocdoperator.js
  tests/cypress/support/index.js
  tests/cypress/templates/argocd_yaml/argocd-operator.yaml
  tests/cypress/templates/argocd_yaml/argocd-resource.yaml
Labels: approved, lgtm

#1067 show resources grouped by namespace
  src-web/actions/topology.js
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/components/Topology/viewer/defaults/details.js
  tests/jest/components/Topology/viewer/defaults/details.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, lgtm

#1070 Task/10739/share toast alert
  src-web/actions/topology.js
  src-web/components/ApplicationTopologyModule/ApplicationTopologyModule.js
  src-web/components/Topology/scss/topology-details.scss
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/components/Topology/viewer/DetailsView.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/ResourceDetails/index.js
  src-web/components/common/ResourceDetails/style.scss
  src-web/components/common/ResourceOverview/index.js
  tests/jest/components/__snapshots__/DetailsView.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_acm.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_argo.test.js.snap
  tests/jest/components/common/ResourceOverview/__snapshots__/ResourceOverview.test.js.snap
Labels: approved, lgtm

#1057 Add argocd tests
  src-web/components/common/OverviewCards/index.js
  tests/cypress/config/config.func.yaml
  tests/cypress/config/index.js
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.js
  tests/cypress/tests/01-create/01-wizard.spec.js
  tests/cypress/tests/01-create/03-git-connection-tests.js
  tests/cypress/tests/02-validate/01-validate-ui-advanced-table.spec.js
  tests/cypress/tests/02-validate/02-validate-ui-app-table.spec.js
  tests/cypress/tests/02-validate/03-validate-ui-single-app.spec.js
  tests/cypress/tests/02-validate/04-validate-backend.spec.js
  tests/cypress/tests/02-validate/05-validate-table-state.spec.js
  tests/cypress/tests/03-edit/01-validate-edit-application-spec.js
  tests/cypress/tests/03-edit/02-edit-application-delete-subs.spec.js
  tests/cypress/tests/03-edit/03-edit-application-delete-subs-validate.spec.js
  tests/cypress/tests/03-edit/04-edit-application-insert-subs.spec.js
  tests/cypress/tests/03-edit/05-edit-application-insert-subs-validate.spec.js
  tests/cypress/tests/04-delete/01-delete-app.spec.js
  tests/cypress/tests/04-delete/02-validate-hub-resource-deletion.spec.js
  tests/cypress/tests/04-delete/03-delete-resources.spec.js
  tests/cypress/tests/rbac_tests/01-create-application-with-rbacuser.js
  tests/cypress/tests/rbac_tests/02-view-application-with-rbacuser.js
  tests/cypress/tests/rbac_tests/03-edit-application-with-rbacuser.js
  tests/cypress/tests/rbac_tests/04-delete-application-with-rbacuser.js
  tests/cypress/views/application.js
  tests/cypress/views/common.js
Labels: approved, lgtm

#1071 update argo server - cluster mapping
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  tests/cypress/config/config.func.yaml
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
Labels: approved, lgtm

#1072 Fix too many svg text nodes created for Argo app count
  src-web/components/Topology/viewer/helpers/nodeHelper.js
Labels: approved, lgtm

#1076 fix argo cluster node status and list
  src-web/actions/topology.js
  src-web/components/Topology/utils/diagram-helpers.js
Labels: approved, lgtm

#1078 update argo label and styling
  nls/platform.properties
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/OverviewCards/style.scss
  tests/cypress.json
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#1080 Add more Argo statuses to error check
  src-web/components/Topology/utils/diagram-helpers-utils.js
Labels: approved, lgtm

#1081 camelcase for kube entities and text wrapping
  nls/platform.properties
  src-web/components/Topology/viewer/defaults/details.js
  src-web/components/Topology/viewer/defaults/titles.js
  src-web/components/Topology/viewer/helpers/nodeHelper.js
  tests/jest/components/Topology/viewer/defaults/details.test.js
  tests/jest/components/Topology/viewer/defaults/titles.test.js
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#1082 address argo server mapping for non ocp clusters
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, lgtm

#1083 show not deployed status for missing argo clusters
  nls/platform.properties
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
Labels: approved, lgtm

#1084 argo app doesn't show not deployed status for ocp clusters
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#1085 UI improvements on subscribed applications
  nls/platform.properties
  src-web/components/ApplicationCreationPage/controlData/ControlDataGit.js
  src-web/components/ApplicationCreationPage/controlData/ControlDataHelm.js
  src-web/components/ApplicationCreationPage/controlData/utils.js
  src-web/components/ApplicationCreationPage/templates/template.hbs
  src-web/components/ApplicationCreationPage/templates/templateGit.hbs
  src-web/components/ApplicationCreationPage/templates/templateHelm.hbs
  src-web/components/ApplicationCreationPage/transformers/transform-data-to-resources.js
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#1087 Update packages
  package-lock.json
  package.json
  scss/variables.scss
  src-web/components/ApplicationCreationPage/style.scss
  src-web/components/ApplicationsListPage.js
  src-web/components/SecondaryHeader.js
  tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/components/__snapshots__/SecondaryHeader.test.js.snap
Labels: approved, lgtm

#1088 Update labels and tooltips for new subscription settings
  nls/platform.properties
  src-web/components/ApplicationCreationPage/templates/templateHelm.hbs
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#1075 Update to the latest AcmHeader
  app.js
  config/config-defaults.json
  controllers/ui/app.js
  lib/shared/config.js
  scss/common.scss
  scss/secondary-header.scss
  src-web/components/ApplicationCreationPage/style.scss
  src-web/components/Topology/scss/resource-toolbar.scss
  src-web/components/common/AutoRefreshSelect.js
  src-web/components/common/OverviewCards/style.scss
  src-web/containers/App.js
  src-web/index.js
  tests/cypress.json
  tests/cypress/tests/02-validate/05-validate-table-state.spec.js
  tests/cypress/views/application.js
  tests/cypress/views/common.js
  tests/jest/components/common/__snapshots__/AutoRefreshSelect_appsTable.test.js.snap
  tests/jest/components/common/__snapshots__/AutoRefreshSelect_singleApp.test.js.snap
  views/home.handlebars
  views/layouts/main.handlebars
Labels: approved, lgtm

#1091 Add Argo app details search and pagination
  nls/platform.properties
  src-web/components/ApplicationTopologyModule/ApplicationTopologyModule.js
  src-web/components/Topology/Topology.js
  src-web/components/Topology/scss/topology-details.scss
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/viewer/ArgoAppDetailsContainer.js
  src-web/components/Topology/viewer/DetailsView.js
  src-web/components/Topology/viewer/DiagramViewer.js
  src-web/components/Topology/viewer/defaults/details.js
  tests/jest/components/Topology/viewer/ArgoAppDetailsContainer.test.js
  tests/jest/components/Topology/viewer/__snapshots__/ArgoAppDetailsContainer.test.js.snap
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#1090 use initial refresh time
  lib/shared/constants.js
  src-web/components/common/AutoRefreshSelect.js
Labels: approved, lgtm

#1092 Argo table grouping
  lib/client/resource-helper.js
  nls/platform.properties
  package-lock.json
  package.json
  src-web/components/common/AutoRefreshSelect.js
  src-web/components/common/ResourceTable.js
  src-web/definitions/hcm-applications.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/config/platform-properties.json
  tests/jest/definitions/__snapshots__/index.test.js.snap
  tests/jest/definitions/hcm-applications.test.js
  tests/jest/lib/client/__snapshots__/resource-helper.test.js.snap
  tests/jest/lib/client/resource-helper.test.js
Labels: approved, lgtm

#1096 use new page header pf-c-page__header
  tests/cypress/support/commands.js
Labels: approved, lgtm

#1094 show warning status if one ns has no resource
  scss/secondary-header.scss
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/defaults/details.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, lgtm

#1089 change links to the targeted application
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/ResourceOverview/utils.js
  tests/cypress/views/application.js
Labels: approved, lgtm

#1093 Add Cypress tests for UI improvements on subscribed applications
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
  tests/cypress/views/application.js
  tests/cypress/views/common.js
Labels: approved, lgtm

#1097 Remove namespace for Argo groups and fix search link
  src-web/definitions/hcm-applications.js
Labels: approved, lgtm

#1103 disable user check on cypress test execution
  tests/cypress/support/commands.js
Labels: approved

#1102 default app topo filter to local-cluster
  src-web/components/ApplicationTopologyModule/ApplicationTopologyModule.js
Labels: approved

#1100 update expandable cards
  package-lock.json
  package.json
  src-web/components/ApplicationDeploymentHighlights/ApplicationDeploymentHighlightsTerminology/index.js
  src-web/components/ApplicationDeploymentHighlights/ApplicationDeploymentHighlightsTerminology/style.scss
  tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap
  tests/jest/components/ApplicationDeploymentHighlights/ApplicationDeploymentHighlightsTerminology/__snapshots__/ApplicationDeploymentHighlightsTerminology.test.js.snap
  tests/jest/components/__snapshots__/ApplicationDeploymentHighlights.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_acm.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_argo.test.js.snap
  tests/jest/components/common/ResourceOverview/__snapshots__/ResourceOverview.test.js.snap
Labels: approved, lgtm

#1099 Fix validation and parsing for time window value
  src-web/components/ApplicationCreationPage/components/TimeWindow.js
Labels: approved, lgtm

#1101 Use topology instead of HCMApplicationList
  src-web/components/common/OverviewCards/index.js
Labels: approved, lgtm

#1105 fix test git commit hash to point to private repo
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
Labels: approved, lgtm

#1106 Display target revision as HEAD when it's not set
  src-web/components/common/OverviewCards/index.js
Labels: approved, lgtm

#1107 remove owners from app-ui
  OWNERS
Labels: approved, lgtm

#1098 Add argocd table test
  tests/cypress/config/config.func.yaml
  tests/cypress/tests/02-validate/02-validate-ui-app-table.spec.js
  tests/cypress/tests/02-validate/03-validate-ui-single-app.spec.js
  tests/cypress/tests/rbac_tests/01-create-application-with-rbacuser.js
  tests/cypress/views/application.js
  tests/package-lock.json
  tests/package.json
Labels: approved, lgtm

#1108 enable cypress validation for logged user name
  nls/platform.properties
  src-web/components/Topology/utils/diagram-helpers-utils.js
  tests/cypress/support/commands.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: no

#1109 Remove space from time window format
  src-web/components/ApplicationCreationPage/components/TimeWindow.js
Labels: approved, dco-signoff: yes, lgtm

#1113 fix secondary header resizing
  scss/secondary-header.scss
  src-web/components/SecondaryHeader.js
  tests/jest/components/SecondaryHeader.test.js
  tests/jest/components/__snapshots__/SecondaryHeader.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1111 add steps
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm

#1116 Add Argo app status to details
  nls/platform.properties
  src-web/components/Topology/viewer/ArgoAppDetailsContainer.js
  tests/jest/components/Topology/viewer/__snapshots__/ArgoAppDetailsContainer.test.js.snap
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1120 fix search bar styling for single app page
  src-web/components/Topology/scss/topology-controls.scss
  src-web/components/common/OverviewCards/style.scss
Labels: approved, dco-signoff: yes, lgtm

#1117 Update README to reflect new chart organization
  README.md
Labels: approved, dco-signoff: yes, lgtm

#1121 Fix cluster count not refreshing
  src-web/components/Topology/viewer/helpers/nodeHelper.js
Labels: approved, dco-signoff: yes, lgtm

#1118 Add content for commit-sign-off
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm

#1122 Display secret ref when selecting existing private repositories
  nls/platform.properties
  src-web/components/ApplicationCreationPage/controlData/ControlDataGit.js
  src-web/components/ApplicationCreationPage/controlData/ControlDataHelm.js
  src-web/components/ApplicationCreationPage/controlData/ControlDataObjectStore.js
  src-web/components/ApplicationCreationPage/controlData/utils.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1123 Exclude MCH Helm repo from available repositories
  src-web/components/ApplicationCreationPage/controlData/utils.js
  tests/jest/components/CreateApplicationPage/controlData/ControlData.test.js
Labels: approved, dco-signoff: yes, lgtm

#1130 no-op change
  README.md
Labels: dco-signoff: no

#1124 show not deployed and offline nodes
  src-web/components/ApplicationTopologyModule/definitions/hcm-application-diagram.js
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/components/Topology/viewer/ClusterDetailsContainer.js
  src-web/components/Topology/viewer/defaults/filtering.js
  src-web/components/Topology/viewer/defaults/status.js
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
  tests/cypress/config/index.js
  tests/jest/components/ApplicationTopologyModule/definitions/hcm-application-diagram.test.js
  tests/jest/components/Topology/viewer/defaults/details.test.js
  tests/jest/components/Topology/viewer/defaults/filtering.test.js
  tests/jest/components/Topology/viewer/defaults/uuu.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, dco-signoff: yes, lgtm

#1128 Show new subscription annotations in topology details
  nls/platform.properties
  src-web/components/Topology/viewer/defaults/details.js
  tests/jest/components/Topology/viewer/defaults/details.test.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1129 Update error message when search not available
  nls/platform.properties
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1135 ansible link missing when no map resource
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, dco-signoff: yes, lgtm

#1136 Use an alternative key for the topology resource map
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, dco-signoff: yes, lgtm

#1138 use argo secrets for cluster name mapping
  src-web/actions/topology.js
  src-web/components/Topology/utils/diagram-helpers-utils.js
  tests/jest/actions/topology.test.js
  tests/jest/components/Topology/viewer/defaults/uuu.test.js
Labels: approved, dco-signoff: yes, lgtm

#1134 Add steps for users to generate their own certs
  .gitignore
  README.md
  build/run-e2e-tests-clusterpool.sh
  build/run-e2e-tests.sh
  sslcert/README.md
  sslcert/req.conf
Labels: approved, dco-signoff: yes, lgtm

#1140 update error msg for unavailable search
  nls/platform.properties
  src-web/actions/topology.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1142 support routes with hash
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  tests/cypress/views/application.js
  tests/cypress/views/common.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, dco-signoff: yes, lgtm

#1139 Support per-row actions in applications table
  nls/platform.properties
  src-web/components/common/ResourceList.js
  src-web/components/common/ResourceTable.js
  src-web/components/common/TableRowActionMenu.js
  src-web/definitions/hcm-applications.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/config/platform-properties.json
  tests/jest/definitions/__snapshots__/index.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1144 Optimize for new "ck creds" behaviour
  build/run-e2e-tests-clusterpool.sh
  run-cypress.sh
Labels: approved, dco-signoff: yes, lgtm

#1146 fix error on sync controller when parent not found
  src-web/components/Topology/utils/diagram-helpers-utils.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
Labels: approved, dco-signoff: yes, lgtm

#1149 fix deploy resource status when not deploying on local cluster
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
Labels: approved, dco-signoff: yes, lgtm

#1148 Fix issue when Argo applications have same name/namespace on different clusters
  src-web/components/common/ResourceTable.js
  src-web/definitions/hcm-applications.js
  tests/cypress/views/application.js
  tests/cypress/views/common.js
  tests/jest/actions/common.test.js
  tests/jest/components/ApplicationsListPage.test.js
  tests/jest/components/TestingData.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/definitions/__snapshots__/index.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1147 set status when no pods for repController
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, dco-signoff: yes, lgtm

#1152 Fix cluster node and Argo app node statuses
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/components/Topology/viewer/ArgoAppDetailsContainer.js
  src-web/components/Topology/viewer/ClusterDetailsContainer.js
  src-web/components/Topology/viewer/defaults/status.js
  tests/jest/components/ApplicationTopologyModule/definitions/hcm-application-diagram.test.js
  tests/jest/components/Topology/viewer/__snapshots__/ArgoAppDetailsContainer.test.js.snap
  tests/jest/components/Topology/viewer/__snapshots__/ClusterDetailsContainer.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1153 add validation for deployedNamespace
  tests/cypress/config/config.func.yaml
  tests/cypress/tests/02-validate/02-validate-ui-app-table.spec.js
  tests/cypress/views/application.js
Labels: approved, dco-signoff: yes, lgtm

#1154 Disable delete for for Argo apps
  src-web/definitions/hcm-applications.js
Labels: approved, dco-signoff: yes, lgtm

#1157 skip refresh if called less then 5s after the last fetch completed
  src-web/components/common/AutoRefreshSelect.js
  src-web/reducers/common.js
  tests/jest/components/TestingData.js
  tests/jest/components/common/AutoRefreshSelect_appsTable.test.js
  tests/jest/components/common/AutoRefreshSelect_singleApp.test.js
  tests/jest/components/common/__snapshots__/AutoRefreshSelect_appsTable.test.js.snap
  tests/jest/components/common/__snapshots__/AutoRefreshSelect_singleApp.test.js.snap
  tests/jest/reducers/common.test.js
Labels: approved, dco-signoff: yes, lgtm

#1156 Task/11795/get local cluster argo route
  src-web/actions/topology.js
Labels: approved, dco-signoff: yes, lgtm

#1158 Fix cluster not selectable from dropdown
  src-web/components/Topology/viewer/ClusterDetailsContainer.js
Labels: approved, dco-signoff: yes, lgtm

#1159 fix code smell
  src-web/components/common/AutoRefreshSelect.js
Labels: approved, dco-signoff: yes, lgtm

#1161 fix e2e issue
  tests/cypress/config/index.js
  tests/cypress/tests/rbac_tests/02-view-application-with-rbacuser.js
Labels: approved, dco-signoff: yes, lgtm

#1160 Fix UI crash when user clicks on cluster node before search finishes loading
  src-web/actions/topology.js
  src-web/components/Topology/viewer/ArgoAppDetailsContainer.js
  src-web/components/Topology/viewer/ClusterDetailsContainer.js
Labels: approved, dco-signoff: yes, lgtm

#1145 Check if redisgraph is deployed before running tests
  tests/cypress/plugins/index.js
  tests/cypress/support/index.js
  tests/start-cypress-tests.sh
Labels: approved, dco-signoff: yes, do-not-merge/hold

#1162 Get Route host information from Console API if hostname is missing
  lib/client/apollo-client.js
  lib/client/queries.js
  nls/platform.properties
  src-web/actions/topology.js
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/components/Topology/viewer/DetailsView.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1163 use search clusters to show app cards cluster status
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/ApplicationTopologyModule/definitions/hcm-application-diagram.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
Labels: approved, dco-signoff: yes, lgtm

#1164 Handle null apiversion on remove resource modal load
  src-web/components/modals/RemoveResourceModal.js
Labels: approved, dco-signoff: yes, lgtm
