Repository stolostron/application-ui, pull requests merged in 2021-05, with the labels that each got.

#1167 fix sonar bug and code smell
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/definitions/hcm-applications.js
Labels: approved, dco-signoff: yes, lgtm

#1169 show argo application set on props dialog, topo
  nls/platform.properties
  src-web/components/Topology/utils/diagram-helpers-argo.js
  src-web/components/Topology/viewer/defaults/details.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-argo.test.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1168 hook nodes should ignore remote clusters
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/TestingData.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, dco-signoff: yes, lgtm

#1166 refactor ansible provider test cases
  README.md
  nls/platform.properties
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
  tests/cypress/config/index.js
  tests/cypress/support/index.js
  tests/cypress/templates/secret_yaml/ansible-secret.yaml
  tests/cypress/views/application.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1170 Add S3 region for object store channels to the application editor
  nls/platform.properties
  src-web/components/ApplicationCreationPage/controlData/ControlDataObjectStore.js
  src-web/components/ApplicationCreationPage/controlData/utils.js
  src-web/components/ApplicationCreationPage/templates/template.hbs
  src-web/components/ApplicationCreationPage/templates/templateObjectStore.hbs
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1171 fail test if oc command fails, wait 60 for cluster name
  tests/cypress/tests/01-create/01-git-connection-tests.js
  tests/cypress/tests/01-create/03-wizard.spec.js
  tests/cypress/views/resources.js
Labels: approved, dco-signoff: yes, lgtm

#1173 Tolerate missing search
  lib/client/apollo-client.js
  lib/client/queries.js
  lib/client/resource-helper.js
  lib/client/search-helper.js
  lib/shared/constants.js
  nls/platform.properties
  src-web/actions/common.js
  src-web/components/common/ResourceTable.js
  src-web/definitions/hcm-applications.js
  src-web/definitions/hcm-channel.js
  src-web/definitions/hcm-placementrule.js
  src-web/definitions/hcm-subscription.js
  tests/jest/components/AdvancedConfigurationPage/AdvancedConfigurationPage.test.js
  tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap
  tests/jest/config/platform-properties.json
  tests/jest/definitions/__snapshots__/index.test.js.snap
  tests/jest/lib/client/search-helper.test.js
Labels: approved, dco-signoff: yes, lgtm

#1172 update handlebars
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#1176 fix resource map when deployables have the same prefix and type
  src-web/components/Topology/utils/diagram-helpers-utils.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
Labels: approved, dco-signoff: yes, lgtm

#1175 Display error for remote app when the cluster is offline
  lib/client/queries.js
  nls/platform.properties
  src-web/actions/common.js
  src-web/actions/index.js
  src-web/actions/topology.js
  src-web/components/ApplicationTopologyModule/ApplicationTopologyModule.js
  src-web/components/common/AutoRefreshSelect.js
  src-web/components/common/OverviewCards/index.js
  src-web/reducers/topology.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1181 Display yellow status for packages with failed phase under subscription statuses
  nls/platform.properties
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1183 update module to move lodash to 4.17.21
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#1186 fixes for postcss
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#1190 updates for y18n rel eng sec
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#1184 show argo app set in main details card
  nls/platform.properties
  package-lock.json
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/ResourceOverview/utils.js
  tests/jest/components/Topology/viewer/__snapshots__/ArgoAppDetailsContainer.test.js.snap
  tests/jest/components/Topology/viewer/defaults/details.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-argo.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
  tests/jest/components/common/ResourceOverview/utils.test.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1193 Detect install namespace dynamically
  tests/cypress/support/index.js
  tests/start-cypress-tests.sh
Labels: approved, dco-signoff: yes, lgtm

#1195 fix canary
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
  tests/cypress/views/resources.js
Labels: approved, dco-signoff: yes, lgtm

#1199 argo editor not opening when cluster not in URL
  src-web/actions/topology.js
  src-web/components/ApplicationTopologyModule/ApplicationTopologyModule.js
  src-web/components/common/AutoRefreshSelect.js
  tests/cypress/tests/02-validate/01-validate-ui-advanced-table.spec.js
  tests/cypress/tests/02-validate/02-validate-ui-app-table.spec.js
Labels: approved, dco-signoff: yes, lgtm

#1201 show deploy status for resources with status info
  src-web/components/Topology/utils/diagram-helpers.js
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
  tests/jest/components/Topology/viewer/utils/diagram-helpers.data.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, dco-signoff: yes, lgtm

#1200 fix error display
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/reducers/data-mappers/mapApplicationsSingle.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, dco-signoff: yes, lgtm

#1203 Fix for 12444 and 12457
  scss/common.scss
  src-web/components/Topology/utils/diagram-helpers-argo.js
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-argo.test.js
Labels: approved, dco-signoff: yes, lgtm

#1202 ApplicationSet grouping
  lib/client/queries.js
  nls/platform.properties
  package-lock.json
  package.json
  src-web/actions/topology.js
  src-web/definitions/hcm-applications.js
  tests/cypress/tests/02-validate/05-validate-table-state.spec.js
  tests/cypress/views/common.js
  tests/jest/config/platform-properties.json
  tests/jest/definitions/__snapshots__/index.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1204 count channel name usage
  src-web/components/ApplicationCreationPage/controlData/utils.js
Labels: approved, dco-signoff: yes, lgtm

#1205 change editor background color to white
  scss/common.scss
  scss/secondary-header.scss
  src-web/components/ApplicationCreationPage/ApplicationCreationPage.js
Labels: approved, dco-signoff: yes, lgtm

#1206 Fix cronjob icon and remove policy node title
  src-web/components/Topology/viewer/defaults/shapes.js
  src-web/components/Topology/viewer/defaults/titles.js
  src-web/components/Topology/viewer/helpers/layoutHelper.js
Labels: approved, dco-signoff: yes, lgtm

#1208 ignore cypress error when requesting token
  tests/cypress/support/commands.js
Labels: approved, dco-signoff: yes, lgtm

#1211 call refresh ui model only when data changed
  src-web/components/ApplicationTopologyModule/definitions/hcm-application-diagram.js
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
Labels: approved, dco-signoff: yes, lgtm

#1207 Add manual application sync button
  nls/platform.properties
  src-web/actions/application.js
  src-web/components/ApplicationCreationPage/transformers/transform-data-to-resources.js
  src-web/components/ApplicationTopologyModule/ApplicationTopologyModule.js
  src-web/components/Topology/Topology.js
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/components/common-apollo/ActionModalApollo.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/OverviewCards/style.scss
  src-web/components/common/ResourceDetails/index.js
  src-web/components/common/ResourceDetails/style.scss
  src-web/components/common/ResourceList.js
  src-web/components/common/ResourceOverview/utils.js
  src-web/components/modals/RemoveResourceModal.js
  src-web/components/modals/SyncResourceModal.js
  tests/cypress/views/application.js
  tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap
  tests/jest/components/TestingData.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/components/common/OverviewCards/OverviewCards.test.js
  tests/jest/components/common/ResourceDetails/ResourceDetails.test.js
  tests/jest/components/common/ResourceDetails/ResourceDetails_acm.test.js
  tests/jest/components/common/ResourceDetails/ResourceDetails_argo.test.js
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_acm.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_argo.test.js.snap
  tests/jest/components/common/ResourceOverview/__snapshots__/ResourceOverview.test.js.snap
  tests/jest/components/common/ResourceOverview/utils.test.js
  tests/jest/components/modal/__snapshots__/RemoveResourceModal.test.js.snap
  tests/jest/components/modal/__snapshots__/RemoveResourceModal_onClose.test.js.snap
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1213 clean up auth cookie when switching users
  tests/cypress/support/commands.js
Labels: approved, dco-signoff: yes, lgtm

#1214 change ansible label
  src-web/components/ApplicationCreationPage/controlData/utils.js
  tests/cypress/config/config.func.yaml
  tests/cypress/templates/secret_yaml/ansible-secret.yaml
Labels: approved, dco-signoff: yes, lgtm

#1215 fix canary (#1195)
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
  tests/cypress/views/resources.js
Labels: dco-signoff: yes, lgtm

#1216 Fix bugs detected by Sonar
  scss/common.scss
  src-web/actions/common.js
  src-web/definitions/hcm-applications.js
Labels: approved, dco-signoff: yes, lgtm

#1217 Add subfolder path for object bucket repositories
  nls/platform.properties
  src-web/components/ApplicationCreationPage/controlData/ControlDataObjectStore.js
  src-web/components/ApplicationCreationPage/templates/template.hbs
  src-web/components/ApplicationCreationPage/templates/templateObjectStore.hbs
  src-web/components/ApplicationCreationPage/transformers/transform-data-to-resources.js
  src-web/components/common/ChannelLabels.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/ResourceOverview/utils.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1219 Disable mouse events and zoom fit diagram during secondaryload
  src-web/components/Topology/viewer/DiagramViewer.js
  tests/jest/components/ApplicationTopologyModule/__snapshots__/ApplicationTopologyModule.test.js.snap
  tests/jest/components/Topology/viewer/__snapshots__/DiagramViewer.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_acm.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_argo.test.js.snap
  tests/jest/components/common/ResourceOverview/__snapshots__/ResourceOverview.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1223 Remove GitHub token where no longer needed
  Makefile
  build/run-e2e-tests-clusterpool.sh
  tests/cypress/scripts/slack-reporter.js
Labels: approved, dco-signoff: yes, lgtm

#1221 Delete all languages other than English
  nls/platform_de.properties
  nls/platform_es.properties
  nls/platform_fr.properties
  nls/platform_it.properties
  nls/platform_ja.properties
  nls/platform_ko.properties
  nls/platform_pt_BR.properties
  nls/platform_zh_CN.properties
  nls/platform_zh_TW.properties
Labels: dco-signoff: yes, lgtm

#1224 Update modals look based on PF guidlines
  Dockerfile.prow
  nls/platform.properties
  src-web/components/common-apollo/ActionModalApollo.js
  src-web/components/modals/RemoveResourceModal.js
  src-web/components/modals/SyncResourceModal.js
  tests/cypress/views/application.js
  tests/jest/components/modal/ModalsTestingData.js
  tests/jest/components/modal/RemoveResourceModal.test.js
  tests/jest/components/modal/RemoveResourceModal_onClose.test.js
  tests/jest/components/modal/__snapshots__/RemoveResourceModal.test.js.snap
  tests/jest/components/modal/__snapshots__/RemoveResourceModal_onClose.test.js.snap
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1225 Advanced tables delete alert
  src-web/actions/common.js
  src-web/components/common-apollo/ActionModalApollo.js
  src-web/reducers/index.js
Labels: approved, dco-signoff: yes, lgtm

#1226 disable RBAC tests
  tests/cypress/tests/rbac_tests/01-create-application-with-rbacuser.js
  tests/cypress/tests/rbac_tests/02-view-application-with-rbacuser.js
  tests/cypress/tests/rbac_tests/03-edit-application-with-rbacuser.js
  tests/cypress/tests/rbac_tests/04-delete-application-with-rbacuser.js
Labels: approved, dco-signoff: yes, lgtm

#1227 enable ansible test
  tests/cypress/config/config.func.yaml
Labels: approved, dco-signoff: yes, lgtm

#1228 Use QueryApplications resource type for modals
  src-web/components/common-apollo/ActionModalApollo.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/modals/RemoveResourceModal.js
  src-web/components/modals/SyncResourceModal.js
  tests/jest/components/modal/RemoveResourceModal.test.js
  tests/jest/components/modal/RemoveResourceModal_onClose.test.js
  tests/jest/components/modal/__snapshots__/RemoveResourceModal.test.js.snap
  tests/jest/components/modal/__snapshots__/RemoveResourceModal_onClose.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1229 Fix app editor alerts
  package-lock.json
  package.json
  tests/cypress/views/application.js
  tests/cypress/views/common.js
Labels: approved, dco-signoff: yes, lgtm

#1231 Update label keys for application modals
  nls/platform.properties
  tests/jest/components/modal/ModalsTestingData.js
  tests/jest/components/modal/__snapshots__/RemoveResourceModal.test.js.snap
  tests/jest/components/modal/__snapshots__/RemoveResourceModal_onClose.test.js.snap
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#1232 Update design for Argo app sets in app table
  nls/platform.properties
  src-web/definitions/hcm-applications.js
Labels: approved, dco-signoff: yes, lgtm

#1230 Make sure success alert appears for advanced delete
  tests/cypress/views/application.js
Labels: approved, dco-signoff: yes, lgtm

#1233 update temptifly to 0.3.32
  Dockerfile
  package-lock.json
  package.json
  tests/cypress/support/commands.js
Labels: approved, dco-signoff: yes, lgtm

#1236 refactor dockerfile
  .dockerignore
  Dockerfile.cypress
  Makefile
Labels: approved, dco-signoff: yes, lgtm

#1238 Remove cookie-utils
  controllers/ui/app.js
  lib/server/cookie-util.js
Labels: approved, dco-signoff: yes, lgtm

#1239 update link icons and colors
  graphics/open-new-tab.svg
  scss/common.scss
  scss/variables.scss
  src-web/components/ApplicationTopologyModule/style.scss
  src-web/components/Topology/scss/topology-details.scss
  src-web/components/Topology/scss/topology-diagram.scss
  src-web/components/Topology/scss/variables.scss
  src-web/components/Topology/viewer/ArgoAppDetailsContainer.js
  src-web/components/Topology/viewer/ClusterDetailsContainer.js
  src-web/components/Topology/viewer/DetailsView.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/OverviewCards/style.scss
  src-web/components/common/ResourceDetails/style.scss
  tests/jest/components/Topology/viewer/__snapshots__/ArgoAppDetailsContainer.test.js.snap
  tests/jest/components/Topology/viewer/__snapshots__/ClusterDetailsContainer.test.js.snap
  tests/jest/components/__snapshots__/DetailsView.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1241 Disable shape replacement in filtering
  src-web/components/Topology/viewer/defaults/filtering.js
Labels: approved, dco-signoff: yes, lgtm

#1198 add an e2e test
  Makefile.prow
  build/run-prow-e2e.sh
Labels: approved, dco-signoff: yes, lgtm

#1243 update packages
  package-lock.json
  package.json
  tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap
  tests/jest/components/CreateApplicationPage/components/__snapshots__/ClusterSelector.test.js.snap
  tests/jest/components/CreateApplicationPage/components/__snapshots__/TimeWindow.test.js.snap
  tests/jest/components/Topology/viewer/__snapshots__/ArgoAppDetailsContainer.test.js.snap
  tests/jest/components/Topology/viewer/__snapshots__/ClusterDetailsContainer.test.js.snap
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1244 Cypress test for sync applications
  tests/cypress/views/application.js
  tests/cypress/views/common.js
Labels: approved, dco-signoff: yes, lgtm

#1245 fix credential url
  src-web/components/ApplicationCreationPage/controlData/ControlDataPrePostTasks.js
Labels: approved, dco-signoff: yes, lgtm

#1240 remove post submit stages in travis
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm

#1242 Fix problem with defining same channel twice in a single app
  src-web/components/ApplicationCreationPage/controlData/utils.js
  tests/cypress/views/resources.js
Labels: approved, dco-signoff: yes, lgtm

#1247 Refactor the tooltip
  nls/platform.properties
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1248 Fix app UI crash
  src-web/components/Topology/viewer/defaults/status.js
Labels: approved, dco-signoff: yes, lgtm

#1253 Fix getSavedPathname
  tests/cypress/views/resources.js
Labels: approved, dco-signoff: yes, lgtm
