Repository stolostron/application-ui, pull requests merged in 2021-09, with the labels that each got.

#1338 Add row actions for appset
  lib/client/apollo-client.js
  lib/client/queries.js
  lib/shared/constants.js
  nls/platform.properties
  package-lock.json
  package.json
  src-web/actions/common.js
  src-web/apollo-client/queries/StateQueries.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/TableRowActionMenu.js
  src-web/components/modals/RemoveResourceModal.js
  src-web/components/modals/SyncResourceModal.js
  src-web/definitions/hcm-applications.js
  src-web/reducers/index.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/config/platform-properties.json
Labels: lgtm, approved, dco-signoff: yes

#1340 Fix placement reverse
  src-web/components/ArgoCreationPage/controlData/ControlDataPlacement.js
  src-web/components/ArgoCreationPage/templates/template.hbs
Labels: lgtm, approved, dco-signoff: yes

#1339 Redirect to table page
  src-web/components/ArgoCreationPage/ArgoCreationPage.js
Labels: lgtm, approved, dco-signoff: yes

#1336 Add exception if there's no clusterset binding
  nls/platform.properties
  src-web/components/ArgoCreationPage/controlData/controlData.js
  src-web/components/ArgoCreationPage/controlData/utils.js
  src-web/components/common/ResourceTable.js
  tests/jest/components/ApplicationsListPage.test.js
  tests/jest/components/CreateArgoPage/__snapshots__/ArgoApplicationPage.test.js.snap
  tests/jest/components/CreateArgoPage/controlData/ControlData.test.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/config/platform-properties.json
Labels: lgtm, approved, dco-signoff: yes

#1341 Fix undefined search filter for remote argo apps
  src-web/components/Topology/utils/diagram-helpers.js
Labels: lgtm, approved, dco-signoff: yes

#1337 Issue15582
  package-lock.json
  package.json
  src-web/components/ArgoCreationPage/ArgoCreationPage.js
  src-web/components/ArgoCreationPage/style.scss
  src-web/components/ArgoCreationPage/transformers/transform-resources-to-controls.js
  tests/cypress/views/application.js
  tests/cypress/views/common.js
  tests/cypress/views/resources.js
  tests/jest/components/CreateArgoPage/__snapshots__/ArgoApplicationPage.test.js.snap
Labels: approved, dco-signoff: yes

#1342 Clarify tooltips for Argo CD app grouping
  nls/platform.properties
  tests/jest/config/platform-properties.json
Labels: lgtm, approved, dco-signoff: yes

#1343 Remove validation for empty table state
  tests/cypress/config/index.js
  tests/cypress/views/common.js
  tests/jest/components/CreateArgoPage/__snapshots__/ArgoApplicationPage.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#1346 Create placement node
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/components/Topology/viewer/defaults/details.js
  tests/jest/components/Topology/viewer/defaults/details.test.js
Labels: lgtm, approved, dco-signoff: yes

#1347 Add table filter and type column
  nls/platform.properties
  package-lock.json
  package.json
  src-web/components/common/LabelWithPopover.js
  src-web/components/common/ResourceTable.js
  src-web/definitions/hcm-applications.js
  tests/cypress/views/application.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/config/platform-properties.json
  tests/jest/definitions/__snapshots__/index.test.js.snap
  tests/jest/definitions/hcm-applications.test.js
Labels: lgtm, approved, dco-signoff: yes

#1348 Disable type column when search is disabled
  src-web/definitions/hcm-applications.js
  tests/jest/definitions/__snapshots__/index.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#1350 Reduce BVT
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
Labels: lgtm, approved, dco-signoff: yes

#1353 Fix unit test failure
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
Labels: lgtm, dco-signoff: yes

#1351 Change app count to use PF badge component
  package-lock.json
  package.json
  scss/table.scss
  src-web/components/common/ChannelLabels.js
  src-web/definitions/hcm-applications.js
  tests/package-lock.json
  tests/package.json
Labels: lgtm, approved, dco-signoff: yes

#1354 Fix placement yaml
  src-web/components/ArgoCreationPage/templates/template.hbs
  tests/cypress.json
  tests/cypress/views/application.js
Labels: lgtm, approved, dco-signoff: yes

#1359 Deliver some last minute design changes to create button and type column
  nls/platform.properties
  package-lock.json
  package.json
  src-web/components/common/ResourceTable.js
  src-web/definitions/hcm-applications.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/config/platform-properties.json
  tests/jest/definitions/hcm-applications.test.js
Labels: lgtm, approved, dco-signoff: yes

#1355 Use smoke test mode for e2e and canary
  Dockerfile.cypress
  Makefile
  build/run-e2e-tests-clusterpool.sh
  build/run-e2e-tests.sh
  package-lock.json
  package.json
  tests/cypress.json
  tests/cypress/README.md
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
  tests/cypress/templates/argocd_yaml/gitopscluster.yaml
  tests/package-lock.json
  tests/package.json
  tests/run-prow-e2e.sh
Labels: lgtm, approved, dco-signoff: yes

#1361 Fix search e2e test failure
  tests/cypress/views/application.js
Labels: lgtm, approved, dco-signoff: yes

#1362 Attempt to fix invalid token issue in canary
  tests/cypress/config/users.yaml
  tests/cypress/support/index.js
  tests/cypress/templates/rbac_yaml/e2e-rbac-clusterrolebinding.yaml
Labels: lgtm, approved, dco-signoff: yes
