Repository stolostron/application-ui, pull requests merged in 2021-06, with the labels that each got.

#1249 Remove translations 2.1
  Dockerfile
  nls/platform_de.properties
  nls/platform_es.properties
  nls/platform_fr.properties
  nls/platform_it.properties
  nls/platform_ja.properties
  nls/platform_ko.properties
  nls/platform_pt_BR.properties
  nls/platform_zh_CN.properties
  nls/platform_zh_TW.properties
  tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap
Labels: dco-signoff: yes, lgtm

#1252 Disable argocd e2e tests on PR builds
  tests/cypress/config/config.func.yaml
  tests/cypress/support/index.js
Labels: approved, dco-signoff: yes, lgtm

#1250 Use openshift gitops operator for argo apps e2e tests
  tests/cypress/config/config.func.yaml
  tests/cypress/scripts/argocd-integration.sh
  tests/cypress/support/argocdoperator.js
  tests/cypress/support/index.js
  tests/cypress/templates/argocd_yaml/argocd-operator.yaml
  tests/cypress/templates/argocd_yaml/argocd-resource.yaml
Labels: approved, dco-signoff: yes, lgtm

#1255 update to latest temptifly version
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#1257 Display zombie clusters
  nls/platform.properties
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1261 Fix subscription propagated status icon in details
  src-web/components/Topology/utils/diagram-helpers.js
Labels: approved, dco-signoff: yes, lgtm

#1260 remove amd64 from image name
  Dockerfile.prow
Labels: approved, dco-signoff: yes, lgtm

#1262 Fix svg download on refresh
  graphics/diagramIcons.svg
  src-web/components/Topology/viewer/ArgoAppDetailsContainer.js
  src-web/components/Topology/viewer/DetailsView.js
  tests/jest/components/Topology/viewer/__snapshots__/ArgoAppDetailsContainer.test.js.snap
  tests/jest/components/__snapshots__/DetailsView.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1258 use console-api query to determine managedcluster
  lib/client/apollo-client.js
  lib/client/queries.js
  src-web/components/ApplicationCreationPage/controlData/ControlDataPlacement.js
  tests/jest/components/CreateApplicationPage/CreateApplicationPage.test.js
  tests/jest/lib/client/resource-helper.test.js
Labels: approved, dco-signoff: yes, lgtm

#1263 Synchronize Dockerfiles for old upstream and Prow
  Dockerfile
  Dockerfile.prow
Labels: approved, dco-signoff: yes, lgtm

#1264 update empty table state
  package-lock.json
  package.json
  src-web/components/common/ResourceTable.js
  tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1265 increase the timeout to create applications
  tests/cypress/config/config.func.yaml
  tests/cypress/support/argocdoperator.js
  tests/cypress/support/index.js
  tests/cypress/tests/01-create/02-wizard.spec.js
  tests/cypress/tests/01-create/03-invalid-tests.spec.js
  tests/cypress/tests/02-validate/01-validate-ui-advanced-table.spec.js
  tests/cypress/views/application.js
  tests/cypress/views/common.js
  tests/cypress/views/resources.js
Labels: approved, dco-signoff: yes

#1267 Upgrade dependences
  package-lock.json
  tests/package-lock.json
Labels: approved, dco-signoff: yes, lgtm

#1266 Fix argocd route
  src-web/actions/topology.js
Labels: approved, dco-signoff: yes

#1268 Fix subscription node status to match status in details
  src-web/components/Topology/utils/diagram-helpers.js
  tests/cypress/tests/02-validate/01-validate-ui-advanced-table.spec.js
Labels: approved, dco-signoff: yes, lgtm

#1269 Update ArgoCD test scripts to use GitOpsCluster CR
  tests/cypress/config/config.func.yaml
  tests/cypress/scripts/argocd-integration.sh
  tests/cypress/support/index.js
  tests/cypress/templates/argocd_yaml/gitopscluster.yaml
  tests/cypress/templates/argocd_yaml/managedclusterset.yaml
  tests/cypress/templates/argocd_yaml/managedclustersetbinding.yaml
  tests/cypress/templates/argocd_yaml/placement.yaml
  tests/cypress/views/application.js
  tests/cypress/views/common.js
Labels: approved, dco-signoff: yes, lgtm

#1271 npm audit fix for glob-parent
  package-lock.json
  tests/jest/components/common/__snapshots__/LabelWithPopover.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1270 Display labels for deployed resources
  src-web/components/Topology/viewer/defaults/details.js
  tests/jest/components/Topology/viewer/defaults/details.test.js
Labels: approved, dco-signoff: yes, lgtm

#1254 Add e2e steps
  Dockerfile.cypress
  Makefile
  Makefile.prow
  build/run-prow-e2e.sh
  tests/cypress/README.md
  tests/cypress/scripts/slack-reporter.js
  tests/package.json
  tests/run-prow-e2e.sh
  tests/start-cypress-tests.sh
Labels: approved, dco-signoff: yes, lgtm

#1272 update cypress and chromedriver version
  package-lock.json
  package.json
  tests/cypress/views/application.js
  tests/cypress/views/common.js
  tests/package-lock.json
  tests/package.json
Labels: approved, dco-signoff: yes, lgtm

#1274 More package updates
  package-lock.json
Labels: approved, dco-signoff: yes, lgtm

#1275 Set subscription status to error when we see propagationfailed
  nls/platform.properties
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1277 fix e2e script and disable cluster validation
  Dockerfile.cypress
  tests/cypress/views/application.js
  tests/cypress/views/common.js
  tests/start-cypress-tests.sh
Labels: approved, dco-signoff: yes, lgtm

#1276 Table overflow fix
  package-lock.json
  package.json
  src-web/components/common/ResourceTable.js
  tests/cypress/config/config.func.yaml
  tests/cypress/views/application.js
  tests/cypress/views/common.js
  tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1279 Turn on cluster count checking
  tests/cypress/views/application.js
  tests/cypress/views/common.js
Labels: approved, dco-signoff: yes, lgtm

#1282 Revert "Turn on cluster count checking (#1279)"
  tests/cypress/views/application.js
  tests/cypress/views/common.js
Labels: approved, dco-signoff: no, lgtm

#1280 Fix resource status not displaying for multisub apps
  src-web/components/Topology/utils/diagram-helpers-utils.js
  tests/jest/components/ApplicationTopologyModule/definitions/hcm-application-diagram.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, dco-signoff: yes, lgtm

#1287 change the 2.2 link to 2.3
  lib/shared/constants.js
  tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap
  tests/jest/components/ApplicationDeploymentHighlights/ApplicationDeploymentHighlightsTerminology/__snapshots__/ApplicationDeploymentHighlightsTerminology.test.js.snap
  tests/jest/components/__snapshots__/ApplicationDeploymentHighlights.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#1285 fix permission restriction
  Dockerfile.cypress
  README.md
  tests/run-prow-e2e.sh
  tests/start-cypress-tests.sh
Labels: approved, dco-signoff: yes, lgtm

#1291 fix slack failure to send video
  tests/cypress/scripts/slack-reporter.js
Labels: approved, dco-signoff: yes, lgtm

#1290 Fix pod details not displaying for multi subs
  src-web/components/Topology/utils/diagram-helpers.js
Labels: approved, dco-signoff: yes, lgtm

#1293 Remove .travis.yml
  .travis.yml
  RELEASE_FF_BRANCH
  RELEASE_MAIN_BRANCH
  RELEASE_VERSION
Labels: approved, dco-signoff: yes, lgtm

#1296 Update tooltip text for private repo secret ref
  nls/platform.properties
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1288 single quote
  nls/platform.properties
  package-lock.json
  package.json
  src-web/components/ApplicationCreationPage/transformers/transform-resources-to-controls.js
Labels: approved, dco-signoff: yes, lgtm

#1294 readonly bug for 2.2
  nls/platform.properties
  package-lock.json
  package.json
Labels: dco-signoff: yes, lgtm

#1298 Implement support for ROSA IDP
  tests/cypress/config/users.yaml
  tests/cypress/support/commands.js
Labels: approved, dco-signoff: yes, lgtm

#1300 Filter out helm properties for search query
  src-web/actions/topology.js
Labels: approved, dco-signoff: yes, lgtm

#1301 change test branch name from master to main
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
  tests/cypress/config/config.rbac.yaml
Labels: approved, dco-signoff: yes, lgtm

#1295 Enable PR tests in Prow
  Dockerfile.cypress
  tests/cypress/plugins/index.js
  tests/cypress/scripts/argocd-integration.sh
  tests/cypress/support/index.js
  tests/cypress/tests/01-create/01-git-connection-tests.js
  tests/cypress/tests/02-validate/02-validate-ui-app-table.spec.js
  tests/cypress/tests/02-validate/03-validate-ui-single-app.spec.js
  tests/cypress/tests/04-delete/01-delete-app.spec.js
  tests/cypress/tests/04-delete/02-validate-hub-resource-deletion.spec.js
  tests/cypress/tests/04-delete/03-delete-resources.spec.js
  tests/download-clis.sh
  tests/run-prow-e2e.sh
Labels: approved, dco-signoff: yes, lgtm

#1303 2.1 change branch name from master to main
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
Labels: dco-signoff: yes, lgtm

#1304 Check for targetRevision and default to HEAD if it doesn't exist
  src-web/actions/topology.js
Labels: approved, dco-signoff: yes, lgtm

#1305 Update ui-components
  package-lock.json
  package.json
  scss/common.scss
  tests/cypress/support/commands.js
  tests/jest/components/modal/__snapshots__/RemoveResourceModal.test.js.snap
  tests/jest/components/modal/__snapshots__/RemoveResourceModal_onClose.test.js.snap
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#1307 Remove master slave
  Makefile
  tests/cypress/config/config.smoke.yaml
  tests/jest/components/ApplicationTopologyModule/ApplicationTopologyModule.test.js
  tests/jest/components/CreateApplicationPage/controlData/ControlData.test.js
  tests/jest/components/TestingData.js
  tests/jest/components/Topology/viewer/ChannelController.test.js
  tests/jest/components/Topology/viewer/defaults/details.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
  tests/jest/components/common/ChannelLabels.test.js
  tests/jest/components/common/ResourceOverview/utils.test.js
  tests/jest/components/modal/RemoveResourceModal.test.js
  vbh/build-harness-extensions/modules/release-ff/Makefile
  vbh/build-harness-extensions/modules/release-ff/bin/release_ff.sh
  vbh/build-harness/.github/workflows/auto-readme.yml
  vbh/build-harness/bin/install.sh
  vbh/build-harness/bin/travis_docker_tag_and_push.sh
Labels: approved, dco-signoff: yes, lgtm

#1310 Update annnotation for Ansible secret so it appears in Credentials
  tests/cypress/templates/secret_yaml/ansible-secret.yaml
Labels: approved, dco-signoff: yes, lgtm

#1311 update to open new tab icon
  src-web/components/ApplicationCreationPage/controlData/ControlDataPrePostTasks.js
Labels: approved, dco-signoff: yes, lgtm
