Repository stolostron/application-ui, pull requests merged in 2021-03, with the labels that each got.

#1003 set default refresh value to 15s
  lib/shared/constants.js
  src-web/components/Topology/viewer/constants.js
  src-web/components/common/AutoRefreshSelect.js
  tests/jest/components/common/__snapshots__/AutoRefreshSelect_appsTable.test.js.snap
  tests/jest/components/common/__snapshots__/AutoRefreshSelect_singleApp.test.js.snap
Labels: approved, lgtm

#998 Fix build image steps
  Makefile
  README.md
Labels: approved, lgtm

#1005 test helm charts with user defined package alias
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
  tests/cypress/views/application.js
Labels: approved, lgtm

#1004 add \n in sonar-project.properties
  sonar-project.properties
Labels: approved, lgtm

#1008 show default status for ansible run as non hook
  src-web/components/Topology/utils/diagram-helpers.js
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved

#1009 remove unnecessary params in dockerfile.prow
  Dockerfile.prow
Labels: approved, lgtm

#1010 no-op change to kickoff prow
  tests/cypress/README.md
Labels: approved, lgtm

#1013 run git api on PR only and remove placement node validation
  tests/cypress/tests/01-create/03-git-connection-tests.js
  tests/cypress/views/application.js
Labels: approved, lgtm

#1012 app-ui image buider
  .dockerignore
  Dockerfile.prow
Labels: approved, lgtm

#1011 Fix table filter sort
  package-lock.json
  package.json
  tests/jest/components/Topology/viewer/__snapshots__/SearchName.test.js.snap
  tests/jest/components/modal/__snapshots__/RemoveResourceModal.test.js.snap
  tests/jest/components/modal/__snapshots__/RemoveResourceModal_onClose.test.js.snap
Labels: approved, lgtm

#1015 use search to get all argo apps with the same source
  src-web/actions/common.js
  src-web/actions/topology.js
  tests/jest/actions/topology.test.js
  tests/jest/components/common/ResourceDetails/ResourceDetails_acm.test.js
  tests/jest/components/common/ResourceDetails/ResourceDetails_argo.test.js
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_acm.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_argo.test.js.snap
Labels: approved, lgtm

#1014 upgrade nodejs version
  .nvmrc
  Dockerfile
  build/run-e2e-tests-clusterpool.sh
  run-cypress.sh
Labels: lgtm

#1018 Support apiVersion and cluster params
  src-web/components/ApplicationTopologyModule/ApplicationTopologyModule.js
  src-web/definitions/hcm-applications.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/definitions/hcm-applications.test.js
Labels: approved, lgtm

#1017 Update overview cards for Argo applications
  lib/client/resource-helper.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/ResourceOverview/utils.js
  tests/jest/components/common/ResourceOverview/utils.test.js
  tests/jest/lib/client/resource-helper.test.js
Labels: approved

#1019 Define e2e tests subset to run as smoke tests
  Makefile
  tests/cypress/config/config.smoke.yaml
  tests/cypress/config/index.js
  tests/cypress/tests/01-create/02-invalid-tests.spec.js
  tests/cypress/tests/01-create/03-git-connection-tests.js
  tests/cypress/tests/02-validate/01-validate-ui-advanced-table.spec.js
  tests/cypress/tests/02-validate/04-validate-backend.spec.js
  tests/start-cypress-tests.sh
Labels: approved, lgtm

#1023 Adopt new ui-components table design
  package-lock.json
  package.json
  src-web/components/common/ResourceTable.js
  tests/cypress/tests/02-validate/05-validate-table-state.spec.js
  tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/components/common/__snapshots__/ResourceList.test.js.snap
Labels: approved, lgtm

#1024 Use security-middleware from npmjs.com
  controllers/ui/index.js
  package-lock.json
  package.json
Labels: approved, lgtm

#1022 Update app overview cards based on Argo CD integration design
  nls/platform.properties
  src-web/components/common/ChannelLabels.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/OverviewCards/style.scss
  src-web/components/common/ResourceOverview/utils.js
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_acm.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_argo.test.js.snap
  tests/jest/components/common/ResourceOverview/__snapshots__/ResourceOverview.test.js.snap
  tests/jest/components/common/ResourceOverview/utils.test.js
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#1026 process helm resources
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, lgtm

#1031 initial step for showing all related apps
  nls/platform.properties
  src-web/actions/common.js
  src-web/actions/topology.js
  src-web/components/Topology/utils/diagram-helpers-utils.js
  tests/cypress/config/config.e2e.yaml
  tests/cypress/config/config.func.yaml
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#1028 Get argocd route app UI
  lib/client/apollo-client.js
  lib/client/queries.js
  nls/platform.properties
  src-web/actions/topology.js
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/components/common/OverviewCards/index.js
  tests/cypress/views/application.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
  tests/jest/components/common/OverviewCards/OverviewCards.test.js
  tests/jest/config/platform-properties.json
Labels: approved, do-not-merge/hold, lgtm

#1037 Update lodash to fix a security issue in 2.2
  package-lock.json
  package.json
  tests/cypress/tests/02-validate/05-validate-table-state.spec.js
  tests/cypress/views/application.js
Labels: lgtm

#1036 Do not show local App/Sub/PR links for child application resources
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/defaults/details.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved

#1038 route timewindow links to edit tab
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/TimeWindowLabels.js
  tests/jest/components/common/OverviewCards/OverviewCards.test.js
  tests/jest/components/common/TimeWindowLabels.test.js
Labels: approved, lgtm

#1041 Top level app sub links 2.2
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/defaults/details.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: lgtm

#1042 Use all source properties in building Argo apps search link
  nls/platform.properties
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/ResourceOverview/utils.js
  tests/jest/components/common/ResourceOverview/utils.test.js
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#1039 Add view resource link for ansible jobs with missing specs.raw.spec
  src-web/components/Topology/utils/diagram-helpers.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, lgtm

#1035 Update lodash for a security issue
  package-lock.json
  package.json
Labels: approved, lgtm

#1044 Do not request selfLink from search queries
  lib/client/queries.js
Labels: approved, lgtm

#1047 allow single app page to show with search service unavailable
  src-web/actions/common.js
  src-web/actions/topology.js
  src-web/components/ApplicationTopologyModule/ApplicationTopologyModule.js
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/viewer/ClusterDetailsContainer.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/ResourceOverview/utils.js
Labels: approved, lgtm

#1048 Skip deleting resources test if running on canary
  tests/cypress/tests/04-delete/01-delete-app.spec.js
  tests/cypress/tests/04-delete/02-validate-hub-resource-deletion.spec.js
  tests/cypress/tests/04-delete/03-delete-resources.spec.js
Labels: approved, lgtm

#1049 argo app - use cluster related from search to set deploy status
  src-web/components/ApplicationTopologyModule/definitions/hcm-application-diagram.js
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/components/Topology/viewer/ClusterDetailsContainer.js
  tests/jest/components/ApplicationTopologyModule/definitions/hcm-application-diagram.test.js
  tests/jest/components/Topology/viewer/ClusterDetailsContainer.test.js
  tests/jest/components/Topology/viewer/__snapshots__/ClusterDetailsContainer.test.js.snap
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, lgtm

#1050 Preserve search on tab change
  src-web/components/ApplicationCreationPage/ApplicationCreationPage.js
  src-web/components/SecondaryHeader.js
Labels: approved, lgtm

#1053 show cluster info from search and target server - argo
  src-web/actions/common.js
  src-web/actions/topology.js
  src-web/components/Topology/utils/diagram-helpers-utils.js
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/components/Topology/viewer/ClusterDetailsContainer.js
  src-web/components/Topology/viewer/DetailsView.js
  src-web/components/Topology/viewer/defaults/status.js
  tests/cypress/config/config.func.yaml
Labels: approved

#1052 Hide editor tab
  src-web/containers/App.js
Labels: approved, lgtm

#1040 fix color
  package-lock.json
  package.json
  src-web/components/ApplicationCreationPage/ApplicationCreationPage.js
Labels: approved, lgtm

#1054 Styling issues
  scss/common.scss
  scss/table.scss
Labels: approved, lgtm

#1055 show error on open argo editor when no route
  src-web/actions/common.js
  src-web/actions/topology.js
Labels: approved, lgtm

#1056 fix offline clusters
  src-web/components/Topology/utils/diagram-helpers-utils.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
Labels: approved, lgtm

#1058 Fix duplicate Argo app node
  src-web/components/ApplicationTopologyModule/definitions/hcm-application-diagram.js
  src-web/components/Topology/viewer/helpers/nodeHelper.js
Labels: approved, lgtm

#1059 fix issue with Set
  src-web/actions/topology.js
  tests/jest/components/Topology/viewer/ClusterDetailsContainer.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Labels: approved, lgtm

#1062 Point users to look at YAML for errors
  nls/platform.properties
  src-web/components/Topology/utils/diagram-helpers-utils.js
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#1064 Show Argo apps in table
  lib/client/queries.js
  nls/platform.properties
  scss/channel-labels.scss
  src-web/components/common/ChannelLabels.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/OverviewCards/style.scss
  src-web/components/common/ResourceTable.js
  src-web/definitions/hcm-applications.js
  src-web/reducers/common.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/config/platform-properties.json
  tests/jest/definitions/__snapshots__/index.test.js.snap
  tests/jest/definitions/hcm-applications.test.js
Labels: approved, lgtm

#1066 fix argo link in details card
  src-web/actions/topology.js
  src-web/components/Topology/scss/topology-details.scss
  src-web/components/Topology/viewer/DetailsView.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/OverviewCards/style.scss
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_acm.test.js.snap
  tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_argo.test.js.snap
  tests/jest/components/common/ResourceOverview/__snapshots__/ResourceOverview.test.js.snap
Labels: approved, lgtm
