Repository stolostron/application-ui, pull requests merged in 2022-08, with the labels that each got.

#1439 Update moment version
  package-lock.json
  package.json
  tests/cypress/README.md
Labels: approved, dco-signoff: yes

#1440 Use ansible early access operator for OCP 4.6
  tests/cypress/support/ansibleoperator.js
  tests/cypress/templates/ansible_yaml/ansible-subscription-early-access.yaml
Labels: lgtm, approved, do-not-merge/hold, dco-signoff: yes

#1443 Ignore error when visiting apps page
  tests/cypress/views/common.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/jest/config/platform-properties.json
Labels: lgtm, approved, dco-signoff: yes
