Repository stolostron/application-ui, pull requests merged in 2022-02, with the labels that each got.

#1411 Update old Travis files
  COMPONENT_VERSION
  tests/cypress/scripts/argocd-integration.sh
Labels: lgtm, approved, do-not-merge/hold, dco-signoff: yes

#1407 Switch to GH org stolostron
  COMPONENT_VERSION
  CONTRIBUTING.md
  Dockerfile.cypress
  Dockerfile.prow
  Makefile
  README.md
  controllers/ui/index.js
  package-lock.json
  package.json
  src-web/components/AdvancedConfigurationLists.js
  src-web/components/ApplicationCreationPage/controlData/ControlDataPlacement.js
  src-web/components/ApplicationCreationPage/controlData/ControlDataPrePostTasks.js
  src-web/components/ApplicationDeploymentHighlights/ApplicationDeploymentHighlightsTerminology/index.js
  src-web/components/ApplicationTopologyModule/ApplicationTopologyModule.js
  src-web/components/ApplicationsListPage.js
  src-web/components/ArgoCreationPage/controlData/controlData.js
  src-web/components/SecondaryHeader.js
  src-web/components/Topology/Topology.js
  src-web/components/Topology/utils/diagram-helpers.js
  src-web/components/Topology/viewer/ChannelControl.js
  src-web/components/common/AutoRefreshSelect.js
  src-web/components/common/ClusterSelector/index.js
  src-web/components/common/OverviewCards/index.js
  src-web/components/common/ResourceDetails/index.js
  src-web/components/common/ResourceList.js
  src-web/components/common/ResourceTable.js
  src-web/components/common/TableRowActionMenu.js
  src-web/components/modals/RemoveResourceModal.js
  src-web/components/modals/SyncResourceModal.js
  src-web/containers/App.js
  tests/cypress/README.md
  tests/cypress/scripts/argocd-integration.sh
  tests/cypress/scripts/slack-reporter.js
  tests/cypress/support/index.js
  tests/cypress/templates/ansible_yaml/ansible-operator-group.yaml
  tests/cypress/templates/ansible_yaml/ansible-subscription.yaml
  tests/cypress/templates/argocd_yaml/argocd-operator.yaml
  tests/cypress/templates/argocd_yaml/managedclustersetbinding.yaml
  tests/cypress/tests/04-delete/03-delete-resources.spec.js
  tests/cypress/views/application.js
  tests/cypress/views/common.js
  tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap
  tests/jest/components/CreateApplicationPage/controlData/ControlData.test.js
  tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
  tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
  tests/run-prow-e2e.sh
  webpack.config.js
Labels: lgtm, approved, dco-signoff: yes

#1413 Fix-argo-install
  tests/cypress/templates/argocd_yaml/argocd-operator.yaml
Labels: lgtm, approved, dco-signoff: yes

#1416 Fix ansble version to be cluster scoped
  tests/cypress/templates/ansible_yaml/ansible-operator-group.yaml
  tests/cypress/templates/ansible_yaml/ansible-subscription.yaml
Labels: lgtm, dco-signoff: yes

#1417 Update ansible to stable channel
  tests/cypress/templates/ansible_yaml/ansible-subscription.yaml
  tests/start-cypress-tests.sh
Labels: lgtm, approved, dco-signoff: yes

#1418 fix ansible yaml failure
  tests/cypress/README.md
  tests/cypress/templates/ansible_yaml/ansible-operator-group.yaml
Labels: lgtm, dco-signoff: yes
